---
title: "244 Lab 3"
author: "Molly Williams"
date: "1/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###0. Attach packages 
```{r packages}

library(boot)
library(naniar)
library(simputation)
library(tidyverse)

```

1. Get penguin data
```{r}

penguins <- read_csv("penguins.csv")

male_p <- penguins %>% 
  filter(sex == "MALE")

# LOOOOK at your data

ggplot(male_p, aes(x = flipper_length)) +
  geom_histogram(bins = 10) +
  theme_light()

# Looking at it you can see the data are not normally distributed; symmetrical ; can't assume normality

flippers <- male_p %>% 
  pull(flipper_length)

# Creates a vector of just the flipper length values from the data frame male_p
```


### Create a function and do some bootstrapping


```{r}

mean_fun <- function(x,i) {mean(x[i])}

# just putting mean(x) doesn't tell it to do multiple bootstrap samples

set.seed(10) # creates a stored index that remembers the order of the random numbers generated; if you want to reproduce something, you need to seed it 
boot_10 <- boot(flippers, mean_fun, R = 10)

set.seed(10)
boot(flippers, mean_fun, R = 10)

boot_100 <- boot(flippers, mean_fun, R = 100) # bias is negative now 


ggplot() +
  aes(boot_100$t) +
  geom_histogram()


boot_10000 <- boot(flippers, mean_fun, R = 10000) # increase the number of bootstrap samples and check for normality

ggplot() +
  aes(boot_10000$t) +
  geom_histogram()

# Look for convergence at a point that's valuable for you 


# Calculate the confidence interval using the boot.ci() function:

boot.ci(boot_10000, conf = 0.95)



```

### Evaluating missingness with naniar 

```{r}

vis_miss(airquality) # airquality is a data set already within R

# Bare minimum missingness assessment; tells you the proportion within each variable of missings; i.e. 24% of ozone observations are missing

gg_miss_var(airquality) # Shows the number missing

# If you want to facet by month:
gg_miss_var(airquality, facet = Month) # only five months in the data set


# Functions to work with ggplot
# geom_miss_point()

ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) +
  geom_point()

# ^ Uses listwise deletion, better:

ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) +
  geom_miss_point()

# Visualizes missing data


ggplot(airquality,
       aes(x = Solar.R,
           y = Temp)) +
  geom_miss_point() +
  scale_color_manual(values = c("orange", "purple")) +
  facet_wrap(~Month)

# Look at see if there seem to be more missing values associated with other variables (month, etc)

# Create a shadow matrix: creates an adjacent copy of your original frame; binary indicator for whether a value was na

na_shadow <- bind_shadow(airquality)

View(airquality)

# Imputation by linear regression ...scarily easy, shouldn't use all the time


airquality %>% 
  impute_lm(Ozone ~ Temp + Wind) %>% 
  ggplot(aes(x = Temp, y = Ozone)) +
  geom_point()
# Not looking great...

na_shadow %>% 
  impute_lm(Ozone ~ Temp + Wind) %>% 
  ggplot(aes(x = Temp, y = Ozone, color=Ozone_NA)) +
  geom_point()

# gives you a very different impression of the data; all the teal points have been imputed (did not originally have a value for ozone)
# always be transparent about how values have been manipulated!

```
















